name = "jikorikai-live"
compatibility_date = "2024-07-01"

[env.production]
name = "jikorikai-live"

[build]
command = "npm run build"
cwd = ""
watch_dir = "src"

[[pages_build_output_dir]]
value = "dist"